BCMOHAD-25104 - Update Handling Error
bcgov/MOH-MAiD pull request #829
Opened 2024-08-19 19:26 UTC by lilianenassar-bib

# Description

BCMOHAD-25104 Update Handling Error

Fixes # (BCMOHAD-25104)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# List high-level changes as bullet items

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ X] Any dependent changes have been merged and published in downstream modules

2024-08-23 16:01 UTC, yashrohan-cgi requested changes
Remove Console .log statements

2024-08-27 21:26 UTC, cgijeffolsen approved these changes
Improved error handling approved @lilianenassar-bib 
@yashrohan-cgi @NataliaNikishina

2024-08-27 21:30 UTC, cgijeffolsen approved these changes
Approved improved methodology with toast. Thank you @lilianenassar-bib 
@yashrohan-cgi @NataliaNikishina

2024-08-27 22:05 UTC, NataliaNikishina approved these changes
@lilianenassar-bib validated and approved

2024-08-27 22:07 UTC, NataliaNikishina commented on MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.js
> +                            console.error('Error deleting record:', error);
Merging PR 829 since it was approved by Jeff

2024-08-27 22:09 UTC, merged